name: MyHome
version: 2.2
author: spathizilla
main: me.taylorkelly.myhome.MyHome
website: http://forums.bukkit.org/threads/13313/
softdepend:
  - Register
  - Help
commands:
  home:
    description: All of the MyHome commands
    usage: /<command> help - Displays the MyHome commands
  myhome:
    description: All of the MyHome commands
    usage: /<command> help - Displays the MyHome commands
    aliases: [mh]
  sethome:
    description: Alias for /home set
    usage: /<command> - Sets the home position if enabled in the configuration